"Você foi contratado para desenvolver um sistema de pagamentos para uma loja online. O sistema deve "
"atender aos seguintes requisitos: "
"1. Todo pagamento deve ter um valor e um método obrigatório processar_pagamento(). "
"○ Isso deve ser definido em uma classe abstrata chamada Pagamento." 
"2. A loja deve aceitar diferentes formas de pagamento (Cartão de Crédito, Pix e Boleto)."
"○ Cada classe filha deve implementar o método abstrato processar_pagamento() de acordo" 
"3. Para garantir que qualquer forma de pagamento possa ser cancelada, crie uma interface Cancelavel "
"que tenha o método abstrato cancelar_pagamento()." 
"○ Todas as classes de pagamento devem implementar essa interface."